deu esse aviso: erro ao buscar alertas, falha ao buscar alertas, provavelmente falta um índice no firestore. verifique o console do firebase para um link para criá-lo (geralmente para 'uid' e 'createdAt' na coleção 'alertas')
e esse issue:

Console Error

FirebaseError: The query requires an index. You can create it here: https://console.firebase.google.com/v1/r/project/clinipratica-d5519/firestore/indexes?create_composite=ClJwcm9qZWN0cy9jbGluaXByYXRpY2EtZDU1MTkvZGF0YWJhc2VzLyhkZWZhdWx0KS9jb2xsZWN0aW9uR3JvdXBzL2FsZXJ0YXMvaW5kZXhlcy9fEAEaBwoDdWlkEAEaDQoJY3JlYXRlZEF0EAIaDAoIX19uYW1lX18QAg

verifiquei que ele está sendo criado no firestore, mas aqui está dando erro, por qual motivo?

informações que pode te ajudar com a estrutura do firestore:
(default)

alertas

appointmentTypes

pacientes

usuarios
alertas

GsYNeB6bGBiNedTIYcrc

JM9nvKcgbguuN4wqDUYM

xKowTuEN2A1gla0u5qtC

zhLqb8KXMzzf6saaQLOl
JM9nvKcgbguuN4wqDUYM
createdAt
29 de maio de 2025 às 12:33:04 UTC-3
(timestamp)

patientId
"squrfdVwJJkksdXwniDx"
(string)

patientName
"Yago Yago"
(string)

patientSlug
"yago-yago"
(string)

reason
"TESTENOVO ALERTA 123"
(string)

uid
"m0fwnuoQJOgQxKb9lwHry2EyftC3"